### PR TITLE
fix: get PW-Test output data via a file instead stdout

### LINKED ISSUE #19: [Bug] Extension does not work if something gets logged inside playwright.config

### PR DESCRIPTION
**Pull request by mxschmitt**
fixes #19

### CODE REVIEW

File: src/playwrightTest.ts [hunk 1]
```diff
@@ -45,31 +46,31 @@ export class PlaywrightTest {
...
-    const proc = await this._executePlaywrightTestCommand(config, projectName, [`${escapeRegExp(path)}:${line}`]);
+  public async runTest(config: PlaywrightTestConfig, projectName: string, testPath: string, line: number): Promise<playwrightTestTypes.JSONReport> {
+    const jsonOutputPath = path.join(os.tmpdir(), createGuid());
+    await this._executePlaywrightTestCommand(jsonOutputPath, config, projectName, [`${escapeRegExp(testPath)}:${line}`]);
     try {
-      return JSON.parse(proc.stdout);
-    } catch (error) {
-      logger.debug('could not parse JSON', proc.stdout, proc.stderr);
-      throw error;
+      return JSON.parse(await fs.promises.readFile(jsonOutputPath, 'utf8'));
```
Comment (mxschmitt) [inline src/playwrightTest.ts:67]: hmm, I should move this maybe into _executePlaywrightTestCommand,

Comment (mxschmitt) [reply src/playwrightTest.ts:67]: nvm, we want exit code validation only for listTests, so not that great.

File: src/playwrightTest.ts [hunk 2]
```diff
@@ -45,31 +46,31 @@ export class PlaywrightTest {
...
+    } finally {
+      await fs.promises.unlink(jsonOutputPath);
     }
   }
 
-  public async runTest(config: PlaywrightTestConfig, projectName: string, path: string, line: number): Promise<playwrightTestTypes.JSONReport> {
-    const proc = await this._executePlaywrightTestCommand(config, projectName, [`${escapeRegExp(path)}:${line}`]);
+  public async runTest(config: PlaywrightTestConfig, projectName: string, testPath: string, line: number): Promise<playwrightTestTypes.JSONReport> {
+    const jsonOutputPath = path.join(os.tmpdir(), createGuid());
```
Comment (aslushnikov) [inline src/playwrightTest.ts:64]: let's prefix this file with something related to the name of this project:

```js
const jsonOutputPath = path.join(os.tmpdir(), 'playwright-vscode-test-exetension-' + createGuid());
```

this way it'll be possible to trace back some leftovers if any.

**Review by aslushnikov — APPROVED** [review]
